apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-deployment
spec:
  selector:
    matchLabels:
      app: wasm-deployment
  template:
    metadata:
      labels:
        app: wasm-deployment
    spec:
      containers:
      - name: wasm-deployment
        image: wasm:v0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
