apiVersion: v1
kind: Service
metadata:
  name: wasm-service
  namespace: wasmedge
  labels:
    app: wasm-deployment
spec:
  selector:
    app: wasm-deployment
  ports:
  - port: 8080
    targetPort: 8080
